### ISSUE TITLE
Can this tool help with configuring steam from the command line?

### ISSUE THREAD

**Issue by tatsujb** [noabody/unibuild#1]
Hi there !

I was brought here by your post over on steam forums : https://steamcommunity.com/app/221410/discussions/0/1734336452578488603/?l=bulgarian&ctp=4#c1742230617613070003

I've been looking for a solution for a while to setting "enable steam for all games" as well as the version of proton from command line : https://github.com/ValveSoftware/steam-for-linux/issues/6121

I'm wondering if you have any insight on this as I see that your script is able to quite a bit. and you have a better understanding than I do of steam's file structure.

**Comment by noabody** [comment]
It depends.  If the game runs in Wine and doesn't have DRM, then yes.

`wstart` can mix and match what proton version (wine) and prefix (virtual file system) a program runs in.  As an example, I could install and run notepad++ via Proton 4.2 in the prefix for say, Assassin's Creed.  I can't run the Steam version of Assassin's Creed in another Proton or prefix.  Best I can do is let Steam run Assassin's Creed in it's own special way.

If you want in install and run something like, Battlefield 1942 with a particular Proton and a standalone _0_ prefix, that should be doable.  Assuming you're running Steam Linux and have Proton installed but haven't launched any games yet, `wstart` tries to build a default _0_ on first run.

Lets say I have the 7zip installer, 7z1900.exe, in ~/Downloads and I want to run it in Proton.  The command is:
```
wstart -pp ~\Downloads
```
Based on the environment variables in the script, as long as the Steam dir is found and `pev` is installed, a menu will be generated that lists _Proton version_ followed by _Proton prefix_ followed by a list of the .exe files in ~\Downloads.

When the install finishes, we run:
```
wstart -pp
```
Just run it by itself and instead of looking for .exe in a particular dir, it'll search for them in the _Proton prefix_ .  It's a little beyond me to document how the script works because:
1) Some days I'm not sure I wrote it.
2) I'm not always sure of what it's supposed to do.
C) My coding/scripting skills are very rudimentary.

**Comment by tatsujb** [comment]
but I do need it for a drm game. 

my current method is to call steam from the terminal and have the user do it himself. 

oh well

**Comment by noabody** [comment]
Sorry, this is more a utility to help manage Wine/Proton prefixes.  Do stuff like `winecfg`, `wineconsole ``cmd`, `winetricks`, etc.  _DRM_ and the Windows _Registry_ really hamper Wine/Proton and `wstart`.

**Comment by noabody** [comment]
As of commit 55ac1c1a62b769b169e3724d60729205fc1d4e4a, it is now possible to "configure" a Proton prefix so to speak.  A Steam DRM protected game can be launched via command ```wstart -ps``` and another program can be run in the same prefix ```wstart -pp``` ... ```proton run? [y/N]```, choose y.  This also applies to all tools: Control Panel, Task Manager, Windows Explorer, Registry Editor, and Command Line.  See my description here [wstart](https://noabody.wordpress.com/2021/10/04/wstart/).

The caveat is that "the other program" may not behave properly.  Game trainers (Cheat Engine, wemod, etc.) will probably not attach to the game as expected.  You can, however use the tools to configure the prefix as needed.
